default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: revo-dev

test:
  <<: *default
  database: revo-test

production:
  <<: *default
  database: revo-pro
